### ISSUE TITLE
Application Defined State Data on SagaSnapshot

### ISSUE THREAD

**Issue by martinzone2000** [event-driven-dotnet/EventDriven.Sagas#1] opened 2022-09-12 17:43 UTC
**Is your feature request related to a problem? Please describe.**
It would be a great benefit to allow the Application to store a piece of state data on the the presentable saga to be available as the saga goes through its steps.  This would allow the application leverage the built in saga infrastructure to maintain data useful durning multiple steps of a saga. 

**Describe the solution you'd like**
My particular use case comes on an update.  My service saves the new object at the beginning of the saga.  However I need to maintain the original object if the saga encounters and error an must be walked back.  To do this I can save my entity locally, but I need to know a tracking Id to I can retrieve it. Since this is part of the saga process it makes since to make this tracking Id in the saga.

**Describe alternatives you've considered**
I could have added the tracking Id directly to the composite entity, But I feel this is really saga related data that has not relevance outside the saga.

**Comment by martinzone2000** [comment] 2022-09-12 17:44
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/9048516/189721213-0c4c61cc-7bf7-4e63-bab0-061bbbbad1d2.png">

**Comment by tonysneed** [comment] 2023-04-03 01:20
Duplicate of #5.

**Closed by tonysneed** 2023-04-03 01:20 UTC
Labels: enhancement
